[workspace]
members = ["ch*"]

[workspace.package]
name = "wgpu_winit_example"
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
winit = { version = "0.30.4" }
pollster = { version = "0.3" }
wgpu = { version = "22.1.0" }
