[package]
name = "ch03_switch_pipeline"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit.workspace = true
pollster.workspace = true
wgpu.workspace = true
